name: Rolling Binary Main
on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '34 12 * * *'

jobs:
  rolling_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: main
      ref_for_scheduled_build: main
